'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Localization
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GoodBroBooter.Localization", GetType(Localization).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 About 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Additional Tasks 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property AdditionalTasks() As String
            Get
                Return ResourceManager.GetString("AdditionalTasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Application path 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ApplicationPath() As String
            Get
                Return ResourceManager.GetString("ApplicationPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Specify the application path... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ApplicationPathBanner() As String
            Get
                Return ResourceManager.GetString("ApplicationPathBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Select application file... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ApplicationPathDialogTitle() As String
            Get
                Return ResourceManager.GetString("ApplicationPathDialogTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Boot app when booter open 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property AutoBoot() As String
            Get
                Return ResourceManager.GetString("AutoBoot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Hide after app booted 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property AutoHide() As String
            Get
                Return ResourceManager.GetString("AutoHide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Quit after app closed 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property AutoQuit() As String
            Get
                Return ResourceManager.GetString("AutoQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Run booter as Administrator to boot application. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property BootAsAdminMessage() As String
            Get
                Return ResourceManager.GetString("BootAsAdminMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Booter Settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property BooterSettings() As String
            Get
                Return ResourceManager.GetString("BooterSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to boot application. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property BootFailedMessage() As String
            Get
                Return ResourceManager.GetString("BootFailedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Boot failed 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property BootFailedMessageTitle() As String
            Get
                Return ResourceManager.GetString("BootFailedMessageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Set resolution, orientation or display frequency failed. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property BootFailedWhileSetDevModeMessage() As String
            Get
                Return ResourceManager.GetString("BootFailedWhileSetDevModeMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Unable to find specified file to boot. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property BootFileNotFoundMessage() As String
            Get
                Return ResourceManager.GetString("BootFileNotFoundMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Boot it!! 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property BootIt() As String
            Get
                Return ResourceManager.GetString("BootIt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Application path or shell statement was not specified. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property BootPathNeededMessage() As String
            Get
                Return ResourceManager.GetString("BootPathNeededMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Boot Settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property BootSettings() As String
            Get
                Return ResourceManager.GetString("BootSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Stop 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property BootStop() As String
            Get
                Return ResourceManager.GetString("BootStop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Configurator path 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ConfiguratorPath() As String
            Get
                Return ResourceManager.GetString("ConfiguratorPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Specify the configurator path... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ConfiguratorPathBanner() As String
            Get
                Return ResourceManager.GetString("ConfiguratorPathBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Select configurator file... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ConfiguratorPathDialogTitle() As String
            Get
                Return ResourceManager.GetString("ConfiguratorPathDialogTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Copy 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CopyMenuHeader() As String
            Get
                Return ResourceManager.GetString("CopyMenuHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Counts... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CountsBanner() As String
            Get
                Return ResourceManager.GetString("CountsBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cut 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CutMenuHeader() As String
            Get
                Return ResourceManager.GetString("CutMenuHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Delay to monitor process 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DelayToMonitorProcess() As String
            Get
                Return ResourceManager.GetString("DelayToMonitorProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Display frequency 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DisplayFrequency() As String
            Get
                Return ResourceManager.GetString("DisplayFrequency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Frequency... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DisplayFrequencyBanner() As String
            Get
                Return ResourceManager.GetString("DisplayFrequencyBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Language 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Language() As String
            Get
                Return ResourceManager.GetString("Language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Max retry count for monitoring 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property MaxRetryCountForProcessMonitoring() As String
            Get
                Return ResourceManager.GetString("MaxRetryCountForProcessMonitoring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Exit 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property MenuExit() As String
            Get
                Return ResourceManager.GetString("MenuExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Stop 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property MenuStop() As String
            Get
                Return ResourceManager.GetString("MenuStop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ms... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property MillisecondBanner() As String
            Get
                Return ResourceManager.GetString("MillisecondBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Executable files|All files 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property OpenApplicationFilterDescription() As String
            Get
                Return ResourceManager.GetString("OpenApplicationFilterDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Open Configurator 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property OpenConfigurator() As String
            Get
                Return ResourceManager.GetString("OpenConfigurator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Run booter as Administrator to open configurator. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property OpenConfiguratorAsAdminMessage() As String
            Get
                Return ResourceManager.GetString("OpenConfiguratorAsAdminMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to open configurator. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property OpenConfiguratorFailedMessage() As String
            Get
                Return ResourceManager.GetString("OpenConfiguratorFailedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cannot open configurator 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property OpenConfiguratorFailedMessageTitle() As String
            Get
                Return ResourceManager.GetString("OpenConfiguratorFailedMessageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Off 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property OptionMarkOff() As String
            Get
                Return ResourceManager.GetString("OptionMarkOff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 On 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property OptionMarkOn() As String
            Get
                Return ResourceManager.GetString("OptionMarkOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Paste 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PasteMenuHeader() As String
            Get
                Return ResourceManager.GetString("PasteMenuHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cannot start post-processing task. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PostProcessingFailedMessage() As String
            Get
                Return ResourceManager.GetString("PostProcessingFailedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Post-process failed 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PostProcessingFailedMessageTitle() As String
            Get
                Return ResourceManager.GetString("PostProcessingFailedMessageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Set resolution, orientation or display frequency back failed. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PostProcessingFailedWhileSetDevModeMessage() As String
            Get
                Return ResourceManager.GetString("PostProcessingFailedWhileSetDevModeMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Process name to moniter 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ProcessName() As String
            Get
                Return ResourceManager.GetString("ProcessName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Specify the process name of the app... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ProcessNameBanner() As String
            Get
                Return ResourceManager.GetString("ProcessNameBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Process priority class 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ProcessPriorityClass() As String
            Get
                Return ResourceManager.GetString("ProcessPriorityClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Above normal 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ProcessPriorityClassAboveNormal() As String
            Get
                Return ResourceManager.GetString("ProcessPriorityClassAboveNormal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Below normal 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ProcessPriorityClassBelowNormal() As String
            Get
                Return ResourceManager.GetString("ProcessPriorityClassBelowNormal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 High 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ProcessPriorityClassHigh() As String
            Get
                Return ResourceManager.GetString("ProcessPriorityClassHigh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Low 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ProcessPriorityClassIdle() As String
            Get
                Return ResourceManager.GetString("ProcessPriorityClassIdle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Normal 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ProcessPriorityClassNormal() As String
            Get
                Return ResourceManager.GetString("ProcessPriorityClassNormal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Real time 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ProcessPriorityClassRealTime() As String
            Get
                Return ResourceManager.GetString("ProcessPriorityClassRealTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Quit booter? 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property QuitMessage() As String
            Get
                Return ResourceManager.GetString("QuitMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Quit 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property QuitMessageTitle() As String
            Get
                Return ResourceManager.GetString("QuitMessageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Resolution 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Resolution() As String
            Get
                Return ResourceManager.GetString("Resolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Width... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ResolutionXBanner() As String
            Get
                Return ResourceManager.GetString("ResolutionXBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Height... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ResolutionYBanner() As String
            Get
                Return ResourceManager.GetString("ResolutionYBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Retry interval for monitoring 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property RetryIntervalForProcessMonitoring() As String
            Get
                Return ResourceManager.GetString("RetryIntervalForProcessMonitoring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Screen orientation 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ScreenOrientation() As String
            Get
                Return ResourceManager.GetString("ScreenOrientation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Landscape (flipped) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ScreenOrientationFlippedLandscape() As String
            Get
                Return ResourceManager.GetString("ScreenOrientationFlippedLandscape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Portrait (flipped) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ScreenOrientationFlippedPortrait() As String
            Get
                Return ResourceManager.GetString("ScreenOrientationFlippedPortrait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Landscape 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ScreenOrientationLandscape() As String
            Get
                Return ResourceManager.GetString("ScreenOrientationLandscape", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Portrait 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ScreenOrientationPortrait() As String
            Get
                Return ResourceManager.GetString("ScreenOrientationPortrait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Shell for another task 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ShellAnotherTask() As String
            Get
                Return ResourceManager.GetString("ShellAnotherTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add another task... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ShellAnotherTaskBanner() As String
            Get
                Return ResourceManager.GetString("ShellAnotherTaskBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Shell for post task 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ShellPostTask() As String
            Get
                Return ResourceManager.GetString("ShellPostTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add a task executed after app closed... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ShellPostTaskBanner() As String
            Get
                Return ResourceManager.GetString("ShellPostTaskBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Shell statement 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ShellStatement() As String
            Get
                Return ResourceManager.GetString("ShellStatement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Specify the shell command to boot... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ShellStatementBanner() As String
            Get
                Return ResourceManager.GetString("ShellStatementBanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Same as system language 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SystemLanguage() As String
            Get
                Return ResourceManager.GetString("SystemLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Abort 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property VbAbort() As String
            Get
                Return ResourceManager.GetString("VbAbort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cancel 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property VbCancel() As String
            Get
                Return ResourceManager.GetString("VbCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Ignore 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property VbIgnore() As String
            Get
                Return ResourceManager.GetString("VbIgnore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property VbNo() As String
            Get
                Return ResourceManager.GetString("VbNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 OK 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property VbOk() As String
            Get
                Return ResourceManager.GetString("VbOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Retry 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property VbRetry() As String
            Get
                Return ResourceManager.GetString("VbRetry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Yes 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property VbYes() As String
            Get
                Return ResourceManager.GetString("VbYes", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
